Pin ldap3 version and update params for SSL validation
nickjer/singularity-rstudio pull request #11
Opened 2021-02-13 05:07 UTC by nhoffman

The behavior of SSL certificate validation seems to have changed in recent versions of ldap3. This PR pins the version of ldap3 to avoid future unexpected changes in behavior, and updates a parameter to cause validation to occur only when a certificate is provided.

Thanks for considering!

2021-05-02 16:42 UTC, nickjer requested changes
Sorry, have not been paying attention to this repo.

2021-05-02 16:42 UTC, nickjer commented on ldap_auth.py
> +[0] A certificate file is only required if mandared by the LDAP host
```suggestion
[0] A certificate file is only required if mandated by the LDAP host
```

2021-06-29 18:05 UTC, nhoffman commented
Thanks for catching that typo (and sorry for the delay).

2021-06-29 22:07 UTC, nickjer approved these changes

2021-06-29 22:07 UTC, merged